spring:
  datasource:
    platform: postgresql
    url: jdbc:postgresql://postgres:5432/adziggy
    name: adziggy
    username: postgres
    password: password
    test-on-borrow: true
    validation-query: SELECT 1
    data: classpath:data-country.sql, classpath:data-city.sql, classpath:data-flight_route.sql
    initialize-mode: always
    continue-on-error: true
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimumIdle: 5
      maximumPoolSize: 20
      idleTimeout: 30000
      poolName: SpringBootJPAHikariCP
      maxLifetime: 2000000
      connectionTimeout: 30000
      connection-test-query: SELECT 1
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      hikari:
        registerMbeans: true
      ddl-auto: create-drop
      connection:
        provider_class: org.hibernate.hikaricp.internal.HikariCPConnectionProvider
    properties:
      org:
        hibernate:
          envers:
            default_schema: data_audit
            global_with_modified_flag: true
      hibernate:
        hbm2ddl:
          import_files: classpath:data-country.sql, classpath:data-city.sql, classpath:data-flight_route.sql
        jdbc:
          lob:
            non_contextual_creation: true
  main:
    web-application-type: servlet
  security:
    user:
      name: user
      password: password
      roles: USER
management:
  endpoints:
    web:
      base-path: /
  server:
    port: 8081
    servlet:
      context-path: /
server:
  servlet:
    context-path: /
  port: 8082